using System.Text;
using Hawkynt.ProcessManager.Model;
using Hawkynt.ProcessManager.Query;
using Hawkynt.ProcessManager.Sampling;

namespace Hawkynt.ProcessManager.Tests;

/// <summary>
/// What an adapter is and what it is attached to (PRD §49) — the parsers, and the rows they end up
/// in. All of it from recorded text, so it is checked on every CI leg with no adapter anywhere near.
/// </summary>
[TestFixture]
public sealed class NetworkPageTests {

  #region the routing table

  private const string _Routes = """
    Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT
    wlp148s0	00000000	012CA8C0	0003	0	0	600	00000000	0	0	0
    wlp148s0	002CA8C0	00000000	0001	0	0	600	00FCFFFF	0	0	0
    enp0s31f6	0000FEA9	00000000	0001	0	0	1000	0000FFFF	0	0	0
    """;

  /// <summary>
  /// The table writes each word in the host's byte order, so 012CA8C0 is 192.168.44.1. Reading it
  /// the other way round produces 1.44.168.192, which is somebody else's machine entirely.
  /// </summary>
  [Test]
  public void TheGatewayIsReadInTheByteOrderTheTableWritesIt() {
    Assert.That(
      RouteTableParser.DefaultGateway(Encoding.UTF8.GetBytes(_Routes), "wlp148s0"),
      Is.EqualTo("192.168.44.1")
    );
  }

  /// <summary>
  /// An interface with routes but no default route has no gateway. The link-local route on the wired
  /// interface is not one, and returning it would send a reader looking for a router that does not
  /// exist.
  /// </summary>
  [Test]
  public void AnInterfaceWithNoDefaultRouteHasNoGateway() {
    Assert.That(RouteTableParser.DefaultGateway(Encoding.UTF8.GetBytes(_Routes), "enp0s31f6"), Is.Null);
    Assert.That(RouteTableParser.DefaultGateway(Encoding.UTF8.GetBytes(_Routes), "eth9"), Is.Null);
  }

  [Test]
  public void TheIpV6DefaultRouteIsTheOneWithAZeroPrefix() {
    const string Table = """
      fe800000000000000000000000000000 40 00000000000000000000000000000000 00 00000000000000000000000000000000 00000100 00000000 00000001 00000001       wlp148s0
      00000000000000000000000000000000 00 00000000000000000000000000000000 00 fe8000000000000012345678abcdef00 00000400 00000000 00000001 00000003       wlp148s0
      """;

    Assert.That(
      RouteTableParser.DefaultGatewayV6(Encoding.UTF8.GetBytes(Table), "wlp148s0"),
      Is.EqualTo("fe80::1234:5678:abcd:ef00")
    );
  }

  /// <summary>
  /// RFC 5952: the longest run of zero groups is elided, and a run of exactly one is not — an
  /// address written both ways does not compare equal to itself by eye.
  /// </summary>
  [Test]
  public void AnIpV6AddressIsWrittenTheWayPeopleWriteIt() {
    Assert.That(IpAddressText.V6([0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), Is.EqualTo("2001:db8::1"));
    Assert.That(IpAddressText.V6([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), Is.EqualTo("::1"));
    Assert.That(IpAddressText.V6([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), Is.EqualTo("::"));
    // One zero group in the middle stays a nought: "::" here would be no shorter and is forbidden.
    Assert.That(
      IpAddressText.V6([0x20, 0x01, 0, 0, 0x0a, 0x0b, 0, 1, 0, 2, 0, 3, 0, 4, 0, 5]),
      Is.EqualTo("2001:0:a0b:1:2:3:4:5")
    );
  }

  #endregion

  #region the resolver

  [Test]
  public void TheNameserversAreReadInOrderAndTheCommentsAreNot() {
    var config = ResolverConfigParser.Parse(Encoding.UTF8.GetBytes("""
      # Generated by NetworkManager
      search hotspot.baho example.test
      nameserver 192.168.44.1
      nameserver 1.1.1.1
      ; a semicolon is a comment too
      """));

    Assert.That(config.Servers, Is.EqualTo(new[] { "192.168.44.1", "1.1.1.1" }));
    Assert.That(config.SearchDomains, Is.EqualTo(new[] { "hotspot.baho", "example.test" }));
    Assert.That(config.IsStubOnly, Is.False);
  }

  /// <summary>
  /// A file whose only server is the stub listener describes this machine talking to itself. The
  /// caller has to know that to go and read the resolver's upstream list instead.
  /// </summary>
  [Test]
  public void TheSystemdStubIsRecognisedForWhatItIs() {
    var config = ResolverConfigParser.Parse(Encoding.UTF8.GetBytes("nameserver 127.0.0.53\noptions edns0\n"));

    Assert.That(config.IsStubOnly, Is.True);
  }

  #endregion

  #region wireless

  private const string _Wireless = """
    Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
     face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
    wlp148s0: 0000   49.  -61.  -256        0      0      0      1    435        0
    """;

  /// <summary>
  /// The figures carry a trailing full stop that is part of the format. Reading past it takes the
  /// next column, which is how a signal level becomes a noise floor.
  /// </summary>
  [Test]
  public void TheSignalLevelIsReadThroughTheTrailingStop() {
    var status = WirelessStatusParser.Find(Encoding.UTF8.GetBytes(_Wireless), "wlp148s0");

    Assert.That(status, Is.Not.Null);
    Assert.That(status!.Value.SignalDbm, Is.EqualTo(-61));
    Assert.That(status.Value.Quality, Is.EqualTo(49));
  }

  [Test]
  public void AWiredInterfaceIsNotInTheFileAndSaysNothing() {
    Assert.That(WirelessStatusParser.Find(Encoding.UTF8.GetBytes(_Wireless), "enp0s31f6"), Is.Null);
  }

  /// <summary>
  /// A driver reporting a relative 0–255 level is using a different unit under the same name, and
  /// showing it as dBm would report an impossibly strong signal.
  /// </summary>
  [Test]
  public void APositiveLevelIsRefusedRatherThanShownAsDbm() {
    const string Relative = """
      Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
       face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
      wlan0: 0000   70.  180.  60        0      0      0      0    0        0
      """;

    var status = WirelessStatusParser.Find(Encoding.UTF8.GetBytes(Relative), "wlan0");
    Assert.That(status, Is.Not.Null);
    Assert.That(status!.Value.SignalDbm, Is.Null);
    Assert.That(status.Value.Quality, Is.EqualTo(70));
  }

  [Test]
  public void AFrequencyIsPlacedOnItsChannelAndItsBand() {
    Assert.That(WirelessChannel.Of(2412), Is.EqualTo(new WirelessChannel.Placement("2.4 GHz", 1)));
    Assert.That(WirelessChannel.Of(2437), Is.EqualTo(new WirelessChannel.Placement("2.4 GHz", 6)));
    // Channel 14 sits twelve megahertz above 13 rather than five, and is the only exception in the
    // whole plan.
    Assert.That(WirelessChannel.Of(2484), Is.EqualTo(new WirelessChannel.Placement("2.4 GHz", 14)));
    Assert.That(WirelessChannel.Of(5180), Is.EqualTo(new WirelessChannel.Placement("5 GHz", 36)));
    Assert.That(WirelessChannel.Of(5955), Is.EqualTo(new WirelessChannel.Placement("6 GHz", 1)));
    Assert.That(WirelessChannel.Of(1234), Is.Null);
  }

  #endregion

  #region a recorded machine is not this one

  /// <summary>
  /// A replayed tree must not be given this machine's addresses (PRD §9.4).
  /// </summary>
  /// <remarks>
  /// <c>getifaddrs</c> and the wireless ioctls answer about the interfaces of the machine running
  /// them and about no others, exactly like <c>CPUID</c> — so a <c>--probe-root</c> replay that
  /// showed this laptop's address and Wi-Fi network beside a fixture's counters would be describing
  /// two machines in one table.
  /// </remarks>
  [Test]
  public void AReplayedInterfaceCarriesNoneOfThisMachinesOwnFacts() {
    var root = Path.Combine(Path.GetTempPath(), $"procman net {Guid.NewGuid():N}");
    var net = Path.Combine(root, "sys", "class", "net", "eth0");
    Directory.CreateDirectory(net);
    File.WriteAllText(Path.Combine(net, "address"), "00:11:22:33:44:55\n");
    File.WriteAllText(Path.Combine(net, "operstate"), "up\n");
    File.WriteAllText(Path.Combine(net, "mtu"), "1500\n");
    File.WriteAllText(Path.Combine(net, "ifindex"), "7\n");
    File.WriteAllText(Path.Combine(net, "type"), "1\n");

    try {
      var recorded = Platform.Linux.LinuxDeviceReader.DescribeInterface(
        Path.Combine(root, "sys"),
        "eth0",
        Path.Combine(root, "proc"),
        live: false
      );

      // What the recorded tree says is read; what only the running kernel can answer is not.
      Assert.That(recorded.MacAddress, Is.EqualTo("00:11:22:33:44:55"));
      Assert.That(recorded.Index, Is.EqualTo(7));
      Assert.That(recorded.Addresses, Is.Null);
      Assert.That(recorded.Ssid, Is.Null);
      Assert.That(recorded.FrequencyMegahertz, Is.Null);
    } finally {
      Directory.Delete(root, recursive: true);
    }
  }

  #endregion

  #region the rows themselves

  private static SystemSnapshot Machine(ulong received, ulong sent) {
    var snapshot = new SystemSnapshot { TimestampTicks = System.Diagnostics.Stopwatch.Frequency };
    snapshot.PrepareProcesses(0);
    snapshot.PrepareNetworks(1)[0] = new() {
      Name = "eth0",
      ReceivedBytes = Counter.Of(received),
      SentBytes = Counter.Of(sent),
      ReceivedPackets = Counter.Of(0),
      SentPackets = Counter.Of(0),
      ReceiveErrors = Counter.Of(0),
      SendErrors = Counter.Of(0),
      ReceiveDropped = Counter.Of(0),
      SendDropped = Counter.Of(0),
    };

    return snapshot;
  }

  private static (SystemSnapshot Snapshot, SnapshotDelta Delta) Moving(ulong bytesEachWay) {
    var before = Machine(0, 0);
    before.TimestampTicks = 0;
    var after = Machine(bytesEachWay, bytesEachWay);
    var delta = new SnapshotDelta();
    delta.Update(before, after, CpuPercentMode.Normalized);
    return (after, delta);
  }

  private static NetworkInterfaceInfo Adapter(Counter speed) => new(
    "eth0",
    "00:11:22:33:44:55",
    speed,
    "up",
    Counter.Of(1500),
    IsLoopback: false,
    Index: 2,
    Kind: "ethernet",
    Driver: "e1000e",
    Addresses: ["10.0.0.5/24"],
    Gateway: "10.0.0.1",
    DnsServers: ["10.0.0.1"]
  );

  private static string Value(IReadOnlyList<PerformanceSection> sections, string label) {
    foreach (var section in sections)
      if (section.Title == "Network — eth0")
        foreach (var row in section.Rows)
          if (row.Label == label)
            return row.Value;

    Assert.Fail($"no row called '{label}'");
    return string.Empty;
  }

  [Test]
  public void AnAdapterSaysWhatItIsAndWhatItIsAttachedTo() {
    var (snapshot, delta) = Moving(1_000_000);
    var sections = PerformanceReport.Build(new(), snapshot, delta, describeInterface: _ => Adapter(Counter.Of(1_000_000_000)));

    Assert.That(Value(sections, "Type"), Is.EqualTo("ethernet · e1000e"));
    Assert.That(Value(sections, "Index"), Is.EqualTo("2"));
    Assert.That(Value(sections, "Address"), Is.EqualTo("10.0.0.5/24"));
    Assert.That(Value(sections, "Gateway"), Is.EqualTo("10.0.0.1"));
    Assert.That(Value(sections, "DNS"), Is.EqualTo("10.0.0.1"));
  }

  /// <summary>
  /// Utilisation needs a link speed. On Wi-Fi and on anything virtual there is none, and a
  /// percentage of a guessed denominator is worse than no percentage at all (PRD §49).
  /// </summary>
  [Test]
  public void UtilisationIsShownOnlyWhereTheLinkSpeedIsKnown() {
    var (snapshot, delta) = Moving(12_500_000);
    var known = PerformanceReport.Build(new(), snapshot, delta, describeInterface: _ => Adapter(Counter.Of(1_000_000_000)));

    // 12.5 MB/s each way is 200 Mbit/s of a gigabit link.
    Assert.That(Value(known, "Utilisation"), Is.EqualTo("20.0 %"));

    var unknown = PerformanceReport.Build(new(), snapshot, delta, describeInterface: _ => Adapter(Counter.NotSupported));
    foreach (var section in unknown)
      if (section.Title == "Network — eth0")
        foreach (var row in section.Rows)
          Assert.That(row.Label, Is.Not.EqualTo("Utilisation"));
  }

  /// <summary>
  /// Two lines within the one network accent, not their sum: an adapter pulling a hundred megabits
  /// and one pushing them draw the same combined line and are not the same machine (PRD §49).
  /// </summary>
  [Test]
  public void ReceiveAndSendAreDrawnAsTwoLines() {
    var (snapshot, delta) = Moving(1_000_000);
    var sections = PerformanceReport.Build(new(), snapshot, delta, describeInterface: _ => Adapter(Counter.NotSupported));

    foreach (var section in sections) {
      if (section.Title != "Network — eth0")
        continue;

      Assert.That(section.Series, Has.Count.EqualTo(1));
      var graph = section.Series[0];
      Assert.That(graph.HasCompanion, Is.True);
      Assert.That(graph.FirstLabel, Is.EqualTo("receive"));
      Assert.That(graph.CompanionLabel, Is.EqualTo("send"));
      Assert.That(graph.Value.Value, Is.EqualTo(1_000_000).Within(1));
      Assert.That(graph.Companion.Value, Is.EqualTo(1_000_000).Within(1));
    }
  }

  /// <summary>
  /// A graph nobody gave a second line to must not be given one: <c>default(Rate)</c> is a confident
  /// zero and would draw a line along the floor (PRD §5.3).
  /// </summary>
  [Test]
  public void AGraphWithNoSecondLineDoesNotClaimOne() {
    var (snapshot, delta) = Moving(1_000_000);
    foreach (var section in PerformanceReport.Build(new(), snapshot, delta))
      foreach (var graph in section.Series)
        if (graph.Label is not ("Transfer rate" or "Throughput"))
          Assert.That(graph.HasCompanion, Is.False, graph.Label);
  }

  /// <summary>
  /// Loopback carries real traffic and is not the network. It has always been excluded from the
  /// rail; the wireless rows must not bring it back by another door.
  /// </summary>
  [Test]
  public void LoopbackIsStillNotAnAdapter() {
    var (snapshot, delta) = Moving(1_000_000);
    var sections = PerformanceReport.Build(
      new(),
      snapshot,
      delta,
      describeInterface: _ => Adapter(Counter.NotSupported) with { IsLoopback = true }
    );

    foreach (var section in sections)
      Assert.That(section.Title, Is.Not.EqualTo("Network — eth0"));
  }

  #endregion

}
